// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFFOBeNNIWYuNcnwx0hXeCYApDIk0nIg',
    appId: '1:1036726572702:web:e03ae93683843bd216cd8f',
    messagingSenderId: '1036726572702',
    projectId: 'accountie-952a8',
    authDomain: 'accountie-952a8.firebaseapp.com',
    storageBucket: 'accountie-952a8.firebasestorage.app',
    measurementId: 'G-BVGBW8SV49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCME-oh98BZLMkZeE5EZoQl71GAdfRdcew',
    appId: '1:1036726572702:android:01debb762169c19f16cd8f',
    messagingSenderId: '1036726572702',
    projectId: 'accountie-952a8',
    storageBucket: 'accountie-952a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANqpuIbzwwb0cbKlrDOehHjSeImfMsbqM',
    appId: '1:1036726572702:ios:c64116d775be377516cd8f',
    messagingSenderId: '1036726572702',
    projectId: 'accountie-952a8',
    storageBucket: 'accountie-952a8.firebasestorage.app',
    androidClientId: '1036726572702-fp3ndg2mtnd3avfm7vuq1098jhebgosf.apps.googleusercontent.com',
    iosClientId: '1036726572702-g3ffitbmm05s4ckc1t64ccsre3a7q6nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANqpuIbzwwb0cbKlrDOehHjSeImfMsbqM',
    appId: '1:1036726572702:ios:c64116d775be377516cd8f',
    messagingSenderId: '1036726572702',
    projectId: 'accountie-952a8',
    storageBucket: 'accountie-952a8.firebasestorage.app',
    androidClientId: '1036726572702-fp3ndg2mtnd3avfm7vuq1098jhebgosf.apps.googleusercontent.com',
    iosClientId: '1036726572702-g3ffitbmm05s4ckc1t64ccsre3a7q6nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtFFOBeNNIWYuNcnwx0hXeCYApDIk0nIg',
    appId: '1:1036726572702:web:40ee206b70c7b6c816cd8f',
    messagingSenderId: '1036726572702',
    projectId: 'accountie-952a8',
    authDomain: 'accountie-952a8.firebaseapp.com',
    storageBucket: 'accountie-952a8.firebasestorage.app',
    measurementId: 'G-7V6F4YZ7E3',
  );
}
